language: cpp
sudo: false

compiler:
  - gcc
#  - clang

env:
  - ANALYZE=false
  - ANALYZE=true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    
    packages:
    - g++-4.8
    - libboost1.55-all-dev
    - git
    - cmake
    - pkg-config
    - libfreetype6-dev
    - libfreeimage-dev
    - libzzip-dev
    - libois-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libopenal-dev
    - libx11-dev
    - libxt-dev
    - libxaw7-dev
    - libxrandr-dev
    - libssl-dev
    - libcurl4-openssl-dev
    - libgtk2.0-dev
    - libwxgtk2.8-dev

before_install:
  # Show some information about the underlying system :nerd:
  - cat /proc/cpuinfo | grep -m1 "model name"  # CPU model

  # Make our build scripts executable
  - chmod +x ./tools/travis/linux/travis.sh
  - chmod +x ./tools/travis/linux/dependencies.sh
  - chmod +x ./tools/travis/linux/build.sh

  # export gcc version to use
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - ./tools/travis/linux/travis.sh

notifications:
  email: false

  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "chat.freenode.net#rigsofrods-dev"
    use_notice: true
    skip_join: true

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cc9257d43908894e2e27
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
